### ISSUE TITLE
Add TKI Nieuw Gas to partners

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etcentral#175]
I have pushed a logo to quintel.com in this commit already: https://github.com/quintel/quintel.com/commit/bc8736623a3677616cbe1a605e50a2c903b4c79c

**Comment by redekok** [comment]
@ChaelKruip Still not entirely sure how it works with the logo images; can we somehow create a link in etcentral to the images in quintel.com?

**Comment by michieldenhaan** [comment]
I think the logos have to be uploaded to AWS. Do you know how to do this @antw?
See https://github.com/quintel/etcentral/pull/169#issuecomment-371122894
and https://github.com/quintel/quintel.com/pull/112

**Comment by antw** [comment]
I have uploaded the images to S3. To add the partner, edit config/partners.yml to add their name and "kind". The "key" should match the image name, which is `tki_nieuw_gas`.

**Comment by redekok** [comment]
@antw Thanks! I'd already updated the config/partners.yml file so that's working properly now (on my `add-tno-to-partnes` branch. As the branch name already implies, I'd also like to add TNO to our partners (https://github.com/quintel/etcentral/issues/174) which requires uploading their images to S3 as well. Is that something we can do ourselves as well, @antw ? If so, could you explain how to do this?

**Comment by antw** [comment]
> I'd also like to add TNO to our partners (#174) which requires uploading their images to S3 as well.

If you send me the images, I can upload them. I don't mind opening up access to S3 for others to upload, but if it's a one-off it's probably easier for me to do it than have to mess with AWS permissions.

**Comment by redekok** [comment]
Sure, I will! However, it might not be a bad idea to grant another Quinteller permission to AWS so that we don't have to bother you with all those minor things? :-) @ChaelKruip what do you think?

**Comment by redekok** [comment]
Done. Closing this issue with https://github.com/quintel/etcentral/pull/176
